"""Added config table

Revision ID: 0cba8268bf04
Revises: 261d97d4709b
Create Date: 2024-01-24 22:31:18.424368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0cba8268bf04'
down_revision = '261d97d4709b'
branch_labels = None
depends_on = None


def upgrade():
    # enum = ENUM("hijri_adjustment", name="configoption", create_type=False)
    # enum.create(op.get_bind(), checkfirst=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('config_option', sa.Enum('hijri_adjustment', name='configoption'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###
