"""Cleaned up optional fields

Revision ID: 1f9d0557e847
Revises: 8d52d9e443f7
Create Date: 2024-01-23 00:13:53.345813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1f9d0557e847'
down_revision = '8d52d9e443f7'
branch_labels = None
depends_on = None


def upgrade():
    enum = ENUM("admin", "masjid_admin", name="userrole", create_type=False)
    enum.create(op.get_bind(), checkfirst=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masjids', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('prayer_times', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('new_role', sa.Enum('admin', 'masjid_admin', name='userrole'), nullable=True))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'masjid_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    ENUM(name="userrole").drop(op.get_bind(), checkfirst=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'masjid_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'new_role')
    op.alter_column('prayer_times', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('masjids', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
