"""Added in enum for user.role

Revision ID: 2d7928204db6
Revises: 366544bc16a1
Create Date: 2024-01-23 00:19:11.298099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d7928204db6'
down_revision = '366544bc16a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'masjid_admin', name='userrole'), nullable=True))
    op.drop_column('users', 'new_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_role', postgresql.ENUM('admin', 'masjid_admin', name='userrole'), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
