"""reset_db_keys

Revision ID: 317d43795cea
Revises: 2d7928204db6
Create Date: 2024-01-23 23:33:38.798056

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '317d43795cea'
down_revision = '2d7928204db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masjids', 'new_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.execute('ALTER TABLE masjids DROP CONSTRAINT masjids_pkey CASCADE')
    op.create_primary_key('masjids_pkey', 'masjids', ['new_id'])

    op.add_column('announcements', sa.Column('new_masjid_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'announcements', 'masjids', ['new_masjid_id'], ['new_id'])
    op.add_column('facilities', sa.Column('new_masjid_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'facilities', 'masjids', ['new_masjid_id'], ['new_id'])
    op.add_column('locations', sa.Column('new_masjid_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'locations', 'masjids', ['new_masjid_id'], ['new_id'])

    op.add_column('prayer_times', sa.Column('new_masjid_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'prayer_times', 'masjids', ['new_masjid_id'], ['new_id'])
    op.add_column('special_prayers', sa.Column('new_masjid_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'special_prayers', 'masjids', ['new_masjid_id'], ['new_id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'masjid_admin', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'masjid_admin', name='userrole'),
               nullable=True)
    op.drop_constraint(None, 'special_prayers', type_='foreignkey')
    op.drop_column('special_prayers', 'new_masjid_id')
    op.drop_constraint(None, 'prayer_times', type_='foreignkey')
    op.drop_column('prayer_times', 'new_masjid_id')

    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'new_masjid_id')
    op.drop_constraint(None, 'facilities', type_='foreignkey')
    op.drop_column('facilities', 'new_masjid_id')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'new_masjid_id')

    op.drop_constraint('masjids_pkey', 'masjids', type_='primary')
    op.create_primary_key('masjids_pkey', 'masjids', ['id'])
    op.alter_column('masjids', 'new_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
