"""update special prayers model with hijri support

Revision ID: a225126bc0d3
Revises: 0cba8268bf04
Create Date: 2024-12-25 22:56:54.248966

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a225126bc0d3'
down_revision = '0cba8268bf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_prayers', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('special_prayers', sa.Column('date_end', sa.Date(), nullable=True))
    op.add_column('special_prayers', sa.Column('is_hijri', sa.Boolean(), nullable=False))
    op.drop_column('special_prayers', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_prayers', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('special_prayers', 'is_hijri')
    op.drop_column('special_prayers', 'date_end')
    op.drop_column('special_prayers', 'date_start')
    # ### end Alembic commands ###
