"""cleanup on foriegn keys and added cascade

Revision ID: b698469eec0b
Revises: 80bfafef871f
Create Date: 2024-01-24 00:05:17.899817

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b698469eec0b'
down_revision = '80bfafef871f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_announcements_masjid_id_masjids', 'announcements', type_='foreignkey')
    op.create_foreign_key('fk_announcements_masjid_id_masjids', 'announcements', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_facilities_masjid_id_masjids', 'facilities', type_='foreignkey')
    op.create_foreign_key('fk_facilities_masjid_id_masjids', 'facilities', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_locations_masjid_id_masjids', 'locations', type_='foreignkey')
    op.create_foreign_key('fk_locations_masjid_id_masjids', 'locations', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_prayer_times_masjid_id_masjids', 'prayer_times', type_='foreignkey')
    op.create_foreign_key('fk_prayer_times_masjid_id_masjids', 'prayer_times', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_special_prayers_masjid_id_masjids', 'special_prayers', type_='foreignkey')
    op.create_foreign_key('fk_special_prayers_masjid_id_masjids', 'special_prayers', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_special_prayers_masjid_id_masjids', 'special_prayers', type_='foreignkey')
    op.create_foreign_key('fk_special_prayers_masjid_id_masjids', 'special_prayers', 'masjids', ['masjid_id'], ['id'])
    op.drop_constraint('fk_prayer_times_masjid_id_masjids', 'prayer_times', type_='foreignkey')
    op.create_foreign_key('fk_prayer_times_masjid_id_masjids', 'prayer_times', 'masjids', ['masjid_id'], ['id'])
    op.drop_constraint('fk_locations_masjid_id_masjids', 'locations', type_='foreignkey')
    op.create_foreign_key('fk_locations_masjid_id_masjids', 'locations', 'masjids', ['masjid_id'], ['id'])
    op.drop_constraint('fk_facilities_masjid_id_masjids', 'facilities', type_='foreignkey')
    op.create_foreign_key('fk_facilities_masjid_id_masjids', 'facilities', 'masjids', ['masjid_id'], ['id'])
    op.drop_constraint('fk_announcements_masjid_id_masjids', 'announcements', type_='foreignkey')
    op.create_foreign_key('fk_announcements_masjid_id_masjids', 'announcements', 'masjids', ['masjid_id'], ['id'])
    # ### end Alembic commands ###
