"""updated tables to all have id fields

Revision ID: e3027fb58e24
Revises: 99998eb2198d
Create Date: 2024-01-20 23:58:15.819600

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3027fb58e24'
down_revision = '99998eb2198d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('masjid_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('masjid_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('date_expired', sa.Date(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_prayers',
    sa.Column('masjid_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('jummuah', 'eid', name='prayertype'), nullable=False),
    sa.Column('info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imam', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('jammat_time', sa.Time(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_announcements_new_masjid_id', table_name='announcements_new')
    op.drop_table('announcements_new')
    op.drop_index('ix_special_prayers_new_date', table_name='special_prayers_new')
    op.drop_index('ix_special_prayers_new_masjid_id', table_name='special_prayers_new')
    op.drop_table('special_prayers_new')
    op.add_column('facilities', sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_index('ix_facilities_masjid_id', table_name='facilities')
    op.drop_constraint('facilities_masjid_id_fkey', 'facilities', type_='foreignkey')
    op.create_foreign_key(None, 'facilities', 'masjids', ['masjid_id'], ['id'])
    op.add_column('locations', sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('locations', 'latitude',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index('ix_locations_geoHash', table_name='locations')
    op.drop_index('ix_locations_masjid_id', table_name='locations')
    op.drop_constraint('locations_masjid_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'masjids', ['masjid_id'], ['id'])
    op.alter_column('masjids', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masjids', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masjids', 'madhab',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masjids', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masjids', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masjids', 'has_times',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('prayer_times', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('prayer_times', sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_index('ix_prayer_times_date', table_name='prayer_times')
    op.drop_index('ix_prayer_times_masjid_id', table_name='prayer_times')
    op.drop_constraint('prayer_times_masjid_id_fkey', 'prayer_times', type_='foreignkey')
    op.create_foreign_key(None, 'prayer_times', 'masjids', ['masjid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prayer_times', type_='foreignkey')
    op.create_foreign_key('prayer_times_masjid_id_fkey', 'prayer_times', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_prayer_times_masjid_id', 'prayer_times', ['masjid_id'], unique=False)
    op.create_index('ix_prayer_times_date', 'prayer_times', ['date'], unique=False)
    op.drop_column('prayer_times', 'id')
    op.drop_column('prayer_times', 'active')
    op.alter_column('masjids', 'has_times',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('masjids', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masjids', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masjids', 'madhab',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masjids', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masjids', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('locations_masjid_id_fkey', 'locations', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_locations_masjid_id', 'locations', ['masjid_id'], unique=False)
    op.create_index('ix_locations_geoHash', 'locations', ['geoHash'], unique=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('locations', 'id')
    op.drop_constraint(None, 'facilities', type_='foreignkey')
    op.create_foreign_key('facilities_masjid_id_fkey', 'facilities', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_facilities_masjid_id', 'facilities', ['masjid_id'], unique=False)
    op.drop_column('facilities', 'id')
    op.create_table('special_prayers_new',
    sa.Column('masjid_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imam', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('jammat_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], name='special_prayers_new_masjid_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('masjid_id', 'type', 'jammat_time', 'label', name='special_prayers_new_pkey')
    )
    op.create_index('ix_special_prayers_new_masjid_id', 'special_prayers_new', ['masjid_id'], unique=False)
    op.create_index('ix_special_prayers_new_date', 'special_prayers_new', ['date'], unique=False)
    op.create_table('announcements_new',
    sa.Column('masjid_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('date_issued', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_expired', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], name='announcements_new_masjid_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('masjid_id', 'date_issued', 'message', name='announcements_new_pkey')
    )
    op.create_index('ix_announcements_new_masjid_id', 'announcements_new', ['masjid_id'], unique=False)
    op.drop_table('special_prayers')
    op.drop_table('announcements')
    op.drop_table('users')
    # ### end Alembic commands ###
