"""inital

Revision ID: ee52a9d7d18f
Revises: 
Create Date: 2023-10-28 02:35:44.922850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee52a9d7d18f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masjids',
    sa.Column('id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('madhab', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('masjid_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('date_expired', sa.Date(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('masjid_id', 'date_expired', 'message')
    )
    op.create_index(op.f('ix_announcements_masjid_id'), 'announcements', ['masjid_id'], unique=False)
    op.create_table('facilities',
    sa.Column('masjid_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('facility', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('masjid_id', 'facility')
    )
    op.create_index(op.f('ix_facilities_masjid_id'), 'facilities', ['masjid_id'], unique=False)
    op.create_table('locations',
    sa.Column('masjid_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('geoHash', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('full_address', sa.String(), nullable=False),
    sa.Column('latitude', sa.BIGINT(), nullable=False),
    sa.Column('longitude', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('masjid_id', 'geoHash')
    )
    op.create_index(op.f('ix_locations_geoHash'), 'locations', ['geoHash'], unique=False)
    op.create_index(op.f('ix_locations_masjid_id'), 'locations', ['masjid_id'], unique=False)
    op.create_table('prayer_times',
    sa.Column('masjid_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fajr_start', sa.TIME(), nullable=False),
    sa.Column('fajr_jammat', sa.TIME(), nullable=False),
    sa.Column('sunrise', sa.TIME(), nullable=False),
    sa.Column('dhur_start', sa.TIME(), nullable=False),
    sa.Column('dhur_jammat', sa.TIME(), nullable=False),
    sa.Column('asr_start', sa.TIME(), nullable=False),
    sa.Column('asr_start_1', sa.TIME(), nullable=False),
    sa.Column('asr_jammat', sa.TIME(), nullable=False),
    sa.Column('magrib_start', sa.TIME(), nullable=False),
    sa.Column('magrib_jammat', sa.TIME(), nullable=False),
    sa.Column('isha_start', sa.TIME(), nullable=False),
    sa.Column('isha_jammat', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('masjid_id', 'date')
    )
    op.create_index(op.f('ix_prayer_times_date'), 'prayer_times', ['date'], unique=False)
    op.create_index(op.f('ix_prayer_times_masjid_id'), 'prayer_times', ['masjid_id'], unique=False)
    op.create_table('special_prayers',
    sa.Column('masjid_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('imam', sa.String(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('jammat_time', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('masjid_id', 'type', 'date', 'label')
    )
    op.create_index(op.f('ix_special_prayers_date'), 'special_prayers', ['date'], unique=False)
    op.create_index(op.f('ix_special_prayers_masjid_id'), 'special_prayers', ['masjid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_special_prayers_masjid_id'), table_name='special_prayers')
    op.drop_index(op.f('ix_special_prayers_date'), table_name='special_prayers')
    op.drop_table('special_prayers')
    op.drop_index(op.f('ix_prayer_times_masjid_id'), table_name='prayer_times')
    op.drop_index(op.f('ix_prayer_times_date'), table_name='prayer_times')
    op.drop_table('prayer_times')
    op.drop_index(op.f('ix_locations_masjid_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_geoHash'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_facilities_masjid_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_announcements_masjid_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_table('masjids')
    # ### end Alembic commands ###
