"""re-added nullable fields

Revision ID: 261d97d4709b
Revises: b698469eec0b
Create Date: 2024-01-24 01:11:48.715675

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '261d97d4709b'
down_revision = 'b698469eec0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_announcements_masjid_id_masjids', 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'masjids', ['masjid_id'], ['id'])
    op.alter_column('facilities', 'info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('fk_facilities_masjid_id_masjids', 'facilities', type_='foreignkey')
    op.create_foreign_key(None, 'facilities', 'masjids', ['masjid_id'], ['id'])
    op.drop_constraint('fk_locations_masjid_id_masjids', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'masjids', ['masjid_id'], ['id'])
    op.alter_column('masjids', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masjids', 'madhab',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masjids', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('masjids', 'email')
    op.alter_column('prayer_times', 'asr_start_1',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_constraint('fk_prayer_times_masjid_id_masjids', 'prayer_times', type_='foreignkey')
    op.create_foreign_key(None, 'prayer_times', 'masjids', ['masjid_id'], ['id'])
    op.drop_constraint('fk_special_prayers_masjid_id_masjids', 'special_prayers', type_='foreignkey')
    op.create_foreign_key(None, 'special_prayers', 'masjids', ['masjid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'special_prayers', type_='foreignkey')
    op.create_foreign_key('fk_special_prayers_masjid_id_masjids', 'special_prayers', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'prayer_times', type_='foreignkey')
    op.create_foreign_key('fk_prayer_times_masjid_id_masjids', 'prayer_times', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    op.alter_column('prayer_times', 'asr_start_1',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.add_column('masjids', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('masjids', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masjids', 'madhab',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masjids', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('fk_locations_masjid_id_masjids', 'locations', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'facilities', type_='foreignkey')
    op.create_foreign_key('fk_facilities_masjid_id_masjids', 'facilities', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    op.alter_column('facilities', 'info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key('fk_announcements_masjid_id_masjids', 'announcements', 'masjids', ['masjid_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
