"""reset primary keys

Revision ID: a7451be87c86
Revises: 317d43795cea
Create Date: 2024-01-23 23:41:55.006127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a7451be87c86'
down_revision = '317d43795cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    # Remove current pkeys
    op.drop_constraint('locations_pkey', 'locations', type_='primary')
    op.drop_constraint('pk_special_prayers', 'special_prayers', type_='primary')
    op.drop_constraint('prayer_times_pkey', 'prayer_times', type_='primary')
    op.drop_constraint('pk_announcements', 'announcements', type_='primary')
    op.drop_constraint('facilities_pkey', 'facilities', type_='primary')
    # Add new pkeys
    op.create_primary_key('locations_pkey', 'locations', ['id'])
    op.create_primary_key('pk_special_prayers', 'special_prayers', ['id'])
    op.create_primary_key('prayer_times_pkey', 'prayer_times', ['id'])
    op.create_primary_key('pk_announcements', 'announcements', ['id'])
    op.create_primary_key('facilities_pkey', 'facilities', ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
        # Remove new pkeys
    op.drop_constraint('locations_pkey', 'locations', type_='primary')
    op.drop_constraint('pk_special_prayers', 'special_prayers', type_='primary')
    op.drop_constraint('prayer_times_pkey', 'prayer_times', type_='primary')
    op.drop_constraint('pk_announcements', 'announcements', type_='primary')
    op.drop_constraint('facilities_pkey', 'facilities', type_='primary')
    # Add current pkeys
    op.create_primary_key('locations_pkey', 'locations', ['id', 'masjid_id'])
    op.create_primary_key('pk_special_prayers', 'special_prayers', ['id', 'masjid_id'])
    op.create_primary_key('prayer_times_pkey', 'prayer_times', ['id', 'masjid_id'])
    op.create_primary_key('pk_announcements', 'announcements', ['masjid_id', 'date_issued', 'message'])
    op.create_primary_key('facilities_pkey', 'facilities', ['id', 'masjid_id'])
