"""migrated id fields

Revision ID: c7c81cf8572f
Revises: e3027fb58e24
Create Date: 2024-01-21 00:36:52.393696

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c7c81cf8572f'
down_revision = 'e3027fb58e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('masjids', sa.Column('new_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('prayer_times', 'id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prayer_times', 'id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('masjids', 'new_id')
    op.alter_column('locations', 'id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
