name: Deploy Lambda API

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'poetry.lock'
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}
  API_GATEWAY_ID: ${{ vars.API_GATEWAY_ID }}
  API_GATEWAY_ROOT_RESOURCE_ID: ${{ vars.API_GATEWAY_ROOT_RESOURCE_ID }}
  PYTHON_VERSION: '3.9.18'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Build Lambda Package
      run: |
        python -m pip install poetry
        make setup-prod
    
    - name: Deploy to Staging
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://lambda.zip
        
        echo "✅ Updated staging environment ($LATEST)"

    - name: Deploy to Production
      id: deploy
      run: |
        # Upload new code and publish version
        VERSION=$(aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://lambda.zip \
          --publish \
          --query 'Version' --output text)
        
        # Update function configuration with commit description
        aws lambda update-function-configuration \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --description "Deployed from commit: ${{ github.sha }}"
        
        # Update production alias to point to new version
        aws lambda update-alias \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --name production \
          --function-version $VERSION
        
        # Get the Lambda ARN with alias instead of version
        LAMBDA_ARN="${{ env.LAMBDA_FUNCTION_NAME }}:production"
        
        # Update API Gateway integration to use alias
        aws apigateway update-integration \
          --rest-api-id ${{ env.API_GATEWAY_ID }} \
          --resource-id ${{ env.API_GATEWAY_ROOT_RESOURCE_ID }} \
          --http-method ANY \
          --patch-operations \
            op=replace,path=/uri,value="arn:aws:apigateway:${AWS_REGION}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS_REGION}:${AWS_ACCOUNT_ID}:function:${LAMBDA_ARN}/invocations"
        
        # Create deployment to make changes live
        aws apigateway create-deployment \
          --rest-api-id ${{ env.API_GATEWAY_ID }} \
          --stage-name v1 \
          --description "Lambda version $VERSION"
        
        echo "✅ Deployed version $VERSION to production"