name: Deploy Lambda API

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'poetry.lock'
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}
  API_GATEWAY_ID: ${{ vars.API_GATEWAY_ID }}
  API_GATEWAY_ROOT_RESOURCE_ID: ${{ vars.API_GATEWAY_ROOT_RESOURCE_ID }}
  PYTHON_VERSION: '3.9.18'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Show first 4 characters of OIDC token
      run: |
        echo "First 4 characters of the token: ${GITHUB_TOKEN:0:4}"

    - name: Debug with PAT
      run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_PAT }}" https://api.github.com/user


    - name: Check OIDC Token
      run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user

    # Set up GitHub CLI using PAT for authentication
    - name: Set up GitHub CLI with PAT
      run: |
          gh auth login --with-token < ${GITHUB_TOKEN}
      env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::026290566452:role/github-actions-role
        aws-region: eu-west-2
        web-identity-token-file: /tmp/oidc_token.jwt
          
    - name: Run AWS command
      run: |
        aws sts get-caller-identity

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Build Lambda Package
      run: |
        python -m pip install poetry
        make setup-prod
    
    - name: Deploy to Staging
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://lambda.zip
        
        echo "✅ Updated staging environment ($LATEST)"

    - name: Deploy to Production
      id: deploy
      run: |
        # Publish new version with commit SHA as description
        VERSION=$(aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://lambda.zip \
          --publish \
          --description "Deployed from commit: ${{ github.sha }}" \
          --query 'Version' --output text)
        
        # Update production alias to point to new version
        aws lambda update-alias \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --name production \
          --function-version $VERSION
        
        # Get the Lambda ARN with alias instead of version
        LAMBDA_ARN="${{ env.LAMBDA_FUNCTION_NAME }}:production"
        
        # Update API Gateway integration to use alias
        aws apigateway update-integration \
          --rest-api-id ${{ env.API_GATEWAY_ID }} \
          --resource-id ${{ env.API_GATEWAY_ROOT_RESOURCE_ID }} \
          --http-method ANY \
          --patch-operations \
            op=replace,path=/uri,value="arn:aws:apigateway:${AWS_REGION}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS_REGION}:${AWS_ACCOUNT_ID}:function:${LAMBDA_ARN}/invocations"
        
        # Create deployment to make changes live
        aws apigateway create-deployment \
          --rest-api-id ${{ env.API_GATEWAY_ID }} \
          --stage-name v1 \
          --description "Lambda version $VERSION"
        
        echo "✅ Deployed version $VERSION to production"